version: '3.4'

services:
  server:
    image: scaffolding-reactjs:dev
    build:
      context: .
      dockerfile: .docker/webserver/Dockerfile
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
