FROM node:lts-alpine AS base
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --silent
COPY [".", "/usr/src/app"]
RUN npm run build:dll
RUN npm run build:prod

# production environment
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
COPY --from=base /usr/src/app/dist /usr/share/nginx/html
COPY .docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
